### ISSUE TITLE
Support nested HackBuilderValues definitions

### ISSUE THREAD

**Issue by fredemmott** [facebookarchive/hack-codegen#12]
For example, I have an `ImmMap<string, ImmMap<string, classname<T>>`; I'd like to codegen the same. `addImmMap()` on that gives me `ImmMap<string, ImmMap<string, string>>`.

I can work around this by codegen'ing separate locals for each variable as immaps with literal values after mapping (`$value ==> "\\".$value.'::class'`), then creating the outer ImmMap from these locals also with literal values. It would be good not to have this intermediate step.

**Comment by alejandromarcu** [comment]
I won't be able to work on this anytime soon (at least 1 month).  If you want to do the change, I'll be happy to review it or to discuss design.
Sorry about that!
